Mimir 707 statistikbank front page
statisticsnorway/mimir pull request #1074
Opened 2021-06-14 07:02 UTC by itemodahl

2021-06-14 14:16 UTC, Garlov requested changes
- Incorrect urls on statistics. See https://www.ssb.no/statbank
- Sort main subjects, sub subjects and statistics alphabetically (if its easy to fix)

2021-06-14 14:16 UTC, Garlov commented on src/main/resources/lib/ssb/dashboard/statistic.ts
> +  // .hits.filter() as unknown as Array<Content<Statistics>>
remove comment

2021-06-16 07:58 UTC, eriksjom approved these changes
Bra jobba! 😍

2021-06-16 07:59 UTC, eriksjom approved these changes

2021-06-16 08:01 UTC, Garlov approved these changes

2021-06-16 08:03 UTC, merged