MIMIR 797 local search filter
statisticsnorway/mimir pull request #1154
Opened 2021-07-12 12:34 UTC by johnnadeluy

2021-08-02 14:30 UTC, Garlov requested changes
From the description in jira, should it be possible for the content-studio user to select the filter manually, or is it supposed to be always on?

And change from result filter to config filter on content-type

2021-08-02 14:30 UTC, Garlov commented on src/main/resources/site/parts/localSearch/localSearch.es6
> +  }).hits.filter((content) => content.type === `${app.name}:statistics` || content.type === `${app.name}:article` || content.type === `${app.name}:page`)
It's better and faster to do the filter in the search config, not on the result

2021-08-04 06:33 UTC, johnnadeluy commented
I believe that the filter is supposed to always be on, so that folders and other content don't get displayed in the results.

2021-08-11 09:26 UTC, Garlov approved these changes
Nice 👍

2021-08-11 09:29 UTC, merged