Mimir 949 add filter searchpage
statisticsnorway/mimir pull request #1328
Opened 2021-11-12 10:50 UTC by ssb-cgn

2021-11-16 09:12 UTC, Glenruben requested changes

2021-11-16 09:12 UTC, Glenruben commented on src/main/resources/site/i18n/phrases.properties
> +filter.limitResult = Agrens treffene
"Avgrens" er feilstavet :)

2021-11-16 09:12 UTC, Glenruben commented on src/main/resources/site/i18n/phrases_nn.properties
> +filter.limitResult = Agrens treffene
tror "Avgrens treffa" vil være mer korrekt
"Avgrens" er feilstavet, og flertallsending på nynorsk er a :)

2021-11-16 09:12 UTC, Glenruben commented on src/main/resources/site/i18n/phrases_nn.properties
> +filter.removeFilterSelection = Fjern alle filtervalg
"Val" på nynorsk, ikke "valg" :)

2021-11-16 14:34 UTC, ssb-cgn commented on src/main/resources/site/i18n/phrases.properties
> +filter.limitResult = Agrens treffene
Fixes

2021-11-16 14:35 UTC, ssb-cgn commented on src/main/resources/site/i18n/phrases_nn.properties
> +filter.limitResult = Agrens treffene
Fixed

2021-11-16 14:35 UTC, ssb-cgn commented on src/main/resources/site/i18n/phrases_nn.properties
> +filter.removeFilterSelection = Fjern alle filtervalg
Fixed

2021-11-17 07:27 UTC, Glenruben approved these changes

2021-11-17 07:34 UTC, merged