Added chat code and feature toggle
statisticsnorway/mimir pull request #1403
Opened 2022-01-06 15:19 UTC by Glenruben

2022-01-07 08:14 UTC, ssb-cgn commented on src/main/resources/site/pages/default/default.html
> +      se.src = 'https://storage.googleapis.com/code.snapengage.com/js/7aa173d9-8793-45b9-b721-9b276d42ff39.js'
Bør man kankje fjerne https: ?, ser i 4.7 at den ligger uten

2022-01-07 08:15 UTC, ssb-cgn commented on src/main/resources/site/pages/default/default.html
> +  <script type="text/javascript" data-th-if="${enabledChatScript}">
Ha en sjekk på at man er på en path som inneholder /innrapportering

2022-01-07 14:10 UTC, ssb-cgn requested changes
Godkjenner Har lagt til noen kommentarer,

2022-01-10 12:50 UTC, Glenruben commented on src/main/resources/site/pages/default/default.html
> +      se.src = 'https://storage.googleapis.com/code.snapengage.com/js/7aa173d9-8793-45b9-b721-9b276d42ff39.js'
Ja fjernet den - gjør det på samme måte her som i siteimprove scriptet.

2022-01-11 07:35 UTC, ssb-cgn commented on src/main/resources/site/pages/default/default.ts
> +    enabledChatScript: isEnabled('enable-chat-script', true, 'ssb') && page._path.startsWith('/innrapportering', 4) // 4 because path starts with /ssb
Hvordan blir det på engelsk da det er /ssb/en?

2022-01-11 07:40 UTC, ssb-cgn approved these changes
Flott 👍

2022-01-11 11:00 UTC, Glenruben commented on src/main/resources/site/pages/default/default.ts
> +    enabledChatScript: isEnabled('enable-chat-script', true, 'ssb') && page._path.startsWith('/innrapportering', 4) // 4 because path starts with /ssb
Godt spørsmål. Har forbedret sjekken!

2022-01-11 11:22 UTC, merged