Mimir 1052 prosjektside
statisticsnorway/mimir pull request #1592
Opened 2022-10-13 13:59 UTC by Sepidk

2022-10-18 09:03 UTC, Glenruben commented on src/main/resources/site/parts/project/project.ts
> +import { Content } from 'enonic-types/content'
Vi bruker ikke enonic-types på denne måten lenger. 
Dokumentasjon på ny versjon av enonic types finner du her: https://github.com/ItemConsulting/enonic-types/releases/tag/0.3.0

2022-10-18 11:20 UTC, Sepidk commented on src/main/resources/site/parts/project/project.ts
> +} = __non_webpack_require__('/lib/util')
It's removed.

2022-10-18 11:21 UTC, Sepidk commented on src/main/resources/site/parts/project/project.ts
> +} = __non_webpack_require__('/lib/ssb/utils/language')
Done.

2022-10-18 14:24 UTC, Glenruben commented on src/main/resources/site/parts/project/project.ts
> +import { Content } from 'enonic-types/content'
Bedre, men vi tillater ikke `// @ts-ignore` i prosjektet. Når du må bruke den så har du gjort noe feil, og det er tilfelle her. Vi tar en prat om det i morgen, så kan vi gå igjennom hele fila - noen biblioteker må byttes ut og brukes riktig.

2022-10-18 14:27 UTC, Glenruben requested changes
Vi går igjennom en del endringer i morgen sammen, vi må sørge for å bruke rett versjon av enonic-types på riktig måte bl.a og det er lite produktivt å lage kommentarer for hver endring i GH.

2022-10-25 13:11 UTC, Glenruben requested changes
Trenger noe arbeid med layout (kan antagelig løses med Bootstrap classes) og noen småting som må fikses. Kjør eslint fix!!

2022-10-25 13:11 UTC, Glenruben commented on src/main/resources/assets/styles/_project.scss
> +  }
Vi bør bruke Bootstrap sine innebygde funksjoner for å gjøre slike ting som dette.
https://getbootstrap.com/docs/5.0/layout/grid/

2022-10-25 13:11 UTC, Glenruben commented on src/main/resources/assets/styles/_project.scss
> +  }
https://getbootstrap.com/docs/5.0/layout/gutters/#no-gutters

2022-10-25 13:11 UTC, Glenruben commented on src/main/resources/assets/styles/_project.scss
> +  }
https://getbootstrap.com/docs/5.0/utilities/spacing/

2022-10-31 15:00 UTC, Glenruben approved these changes
Fikset et par småting, men nå ser siden mye bedre ut! 👍

2022-11-01 09:34 UTC, merged