Mimir 1553 improvements pif calculator
statisticsnorway/mimir pull request #2067
Opened 2023-08-29 10:28 UTC by johnnadeluy

2023-08-29 10:31 UTC, omsaggau commented on src/main/resources/react4xp/_entries/PifCalculator.jsx
> +          <Link className='float-md-end stand-alone' href={props.calculatorArticleUrl}>
Link har prop standAlone, heller benytte den?

`<Link className='float-md-end' standAlone>`

2023-09-04 07:21 UTC, omsaggau requested changes

2023-09-04 07:21 UTC, omsaggau commented on src/main/resources/services/pif/pif.ts
> +  const scopeCode: string | undefined = req.params?.scopeCode ?? '3'
Hva er scopeCode og hva er betyr 3 her i denne kontekts? 
Kanskje bruke en enum her eller noen kommentarer, ellers så blir dette litt magic numbery

2023-09-04 13:09 UTC, ssb-cgn approved these changes
Nice 👍

2023-09-05 06:48 UTC, omsaggau approved these changes

2023-09-12 06:11 UTC, merged