[MIM-1696] Mim 1696 screenreader kpi name calculator
statisticsnorway/mimir pull request #2326
Opened 2023-12-08 14:48 UTC by ssb-cgn

[Link to ticket: MIM-1696](https://statistics-norway.atlassian.net/browse/MIM-1696)

2023-12-11 10:38 UTC, Glenruben requested changes
Ryddig og pent, men se kommentar om Title elementet. Hvorfor er det bytta ut med h3?

2023-12-11 10:38 UTC, Glenruben commented on src/main/resources/react4xp/_entries/KpiCalculator.jsx
> +            <h3 className='ssb-title'>{props.phrases.amountEqualled}</h3>
Hvorfor vil du endre dette til h3 tag? Og hvorfor bare her, og ikke på forside?

2023-12-12 07:40 UTC, ssb-cgn commented on src/main/resources/react4xp/_entries/KpiCalculator.jsx
> +            <h3 className='ssb-title'>{props.phrases.amountEqualled}</h3>
Var før jeg la aria-hidden til col da la jeg den på h3, men skal endre tilbake nå :)

2023-12-12 13:31 UTC, Glenruben approved these changes

2023-12-14 10:16 UTC, merged