Mim 858 - GA_TRACKING_ID and gtag removal
statisticsnorway/mimir pull request #2767
Opened 2024-05-30 11:33 UTC by Carl-OW

2024-05-30 12:07 UTC, Carl-OW commented
Best å merge denne PRen før vi prøver å merge MIM-1887-removal-of-universal-analytics igjen

2024-05-30 12:29 UTC, closed without merging

2024-05-31 06:23 UTC, ssb-cgn commented on src/main/resources/react4xp/_entries/AttachmentTablesFigures.tsx
> -  function toggleAccordion(isOpen: boolean, index: number) {
Må fjerne kall til toggleAccordion på Accordion lengre ned i koden `onToggle={(isOpen: boolean) => toggleAccordion(isOpen, index)}`

2024-05-31 06:32 UTC, ssb-cgn commented on src/main/resources/site/parts/links/links.tsx
>    const handleClick = () => {
Kan nok fjerne denne tomme funksjonen og referansen til den i Link komponenten lengre ned

2024-05-31 06:41 UTC, ssb-cgn commented on src/main/resources/site/parts/searchResult/searchResultView.tsx
> -  const [numberChanged, setNumberChanged] = useState(0)
Denne må ikke fjernes

2024-05-31 06:41 UTC, ssb-cgn commented on src/main/resources/site/parts/searchResult/searchResultView.tsx
> -      setNumberChanged((prev) => prev + 1)
Ikke fjern denne

2024-05-31 06:42 UTC, ssb-cgn commented on src/main/resources/site/parts/searchResult/searchResultView.tsx
> -    if (mainNameResult && mainNameResult.count && !filterChanged && numberChanged === 0) {
If setningen må være som før, kun fjerne addGtagForEvent

2024-05-31 06:48 UTC, ssb-cgn requested changes
Må fikse det som er kommentert