Mimir 672 manual refresh statreg
statisticsnorway/mimir pull request #407
Opened 2020-08-27 09:07 UTC by erikgus

2020-08-28 09:06 UTC, johnnadeluy requested changes
After pressing the refresh button for statreg, is the green popup supposed to be empty?

2020-08-30 09:26 UTC, erikgus commented on src/test/resources/lib/ssb/keyFigure-test.es6
> +const test = __non_webpack_require__('/lib/xp/testing')
Yes, snuck itself in. removed now.

2020-08-30 09:30 UTC, erikgus commented on src/main/resources/react4xp/_entries/Dashboard/Dashboard.jsx
> +                </div>
removed

2020-08-30 11:14 UTC, erikgus commented on src/main/resources/react4xp/_entries/Dashboard/RefreshDataButton.jsx
> +          const message = err
fixd

2020-08-31 09:13 UTC, johnnadeluy approved these changes
Good work! 🙌

2020-08-31 15:34 UTC, merged