MIMIR-793: Debugging of components coming and going
statisticsnorway/mimir pull request #430
Opened 2020-09-09 08:57 UTC by itemodahl

Add logging of stickymenu render result length
Remove unnecessery setting of id
Change id of footer component to reactfooter to check if it is something else with the same id
Remove a required options on menubox alt description since it is making warnings

2020-09-23 11:45 UTC, Garlov requested changes

2020-09-23 11:45 UTC, Garlov commented on .drone.yml
> +    - MIMIR-793-debuggingComponentsDisapearing
remove branch trigger for drone

2020-09-23 11:45 UTC, Garlov commented on src/main/resources/site/pages/default/default.es6
> +  log.info('Add id %s', JSON.stringify(breadcrumbComponent.renderBody(), null, 2))
remove log and comment

2020-09-23 11:45 UTC, Garlov commented on src/main/resources/site/pages/default/default.es6
> +function addAlerts(alerts, body, pageContributions ){
lint

2020-09-23 11:45 UTC, Garlov commented on src/main/resources/site/pages/default/default.es6
> +    { body: bodyWithBreadCrumbs, pageContributions }
lint

2020-10-08 07:18 UTC, itemodahl commented on .drone.yml
> +    - MIMIR-793-debuggingComponentsDisapearing
removed

2020-10-08 07:18 UTC, itemodahl commented on src/main/resources/site/pages/default/default.es6
> +function addAlerts(alerts, body, pageContributions ){
linted

2020-10-08 07:18 UTC, itemodahl commented on src/main/resources/site/pages/default/default.es6
> +    { body: bodyWithBreadCrumbs, pageContributions }
linted

2020-10-08 07:53 UTC, Garlov approved these changes

2020-10-08 07:54 UTC, merged