Mimir 816 react app dashboard
statisticsnorway/mimir pull request #466
Opened 2020-10-01 11:07 UTC by Garlov

2020-10-01 12:26 UTC, johnnadeluy requested changes
Aside from the other known w3c validator errors that can be ignored, there's also: (Error) '_Bad value https://fonts.googleapis.com/css?family=Open+Sans|Open+Sans:700|Roboto:700|Roboto+Condensed:700 for attribute href on element link: Illegal character in query: | is not allowed._' 
And (Warning) '_The type attribute is unnecessary for JavaScript resources._'


Only nitpicky stuff on this review, but the code is very clean and well-structured - easy to follow through! Great job!! 😊

2020-10-01 12:26 UTC, johnnadeluy commented on src/main/resources/react4xp/_entries/Dashboard/utils/websocket/WebsocketProvider.jsx
> +import setupDataQuieriesListeners from '../../containers/DataQueries/listeners'
setupDataQuieresListeners -> setupDataQueriesListeners?  @ both import and function call

2020-10-01 13:30 UTC, Garlov commented on src/main/resources/admin/tools/dashboard/dashboard.html
>      <meta http-equiv="Cache-control" content="NO-CACHE"></meta>
Wont touch this now, we'll have to look at this later

2020-10-02 06:55 UTC, johnnadeluy approved these changes
👏😊

2020-10-05 14:20 UTC, merged