MIMIR-73: Use title from tbprocessor data if it exists
statisticsnorway/mimir pull request #498
Opened 2020-10-13 08:59 UTC by itemodahl

Move code to lib

MIMIR-73

2020-10-14 13:01 UTC, Garlov requested changes

2020-10-14 13:01 UTC, Garlov commented on src/main/resources/lib/ssb/table.ts
> +const util: UtilLibrary = __non_webpack_require__( '/lib/util')
linting: unused

2020-10-14 13:01 UTC, Garlov commented on src/main/resources/lib/ssb/table.ts
>  } = __non_webpack_require__('/lib/ssb/cache')
SSBCacheLibrary interface

2020-10-14 14:02 UTC, itemodahl commented on src/main/resources/lib/ssb/keyFigure.ts
>  } = __non_webpack_require__('/lib/ssb/cache')
added

2020-10-14 14:02 UTC, itemodahl commented on src/main/resources/lib/ssb/table.ts
>  } = __non_webpack_require__('/lib/ssb/cache')
added

2020-10-14 14:03 UTC, itemodahl commented on src/main/resources/lib/ssb/table.ts
> +const util: UtilLibrary = __non_webpack_require__( '/lib/util')
removed

2020-10-15 07:44 UTC, Garlov approved these changes
Looks good 👍

2020-10-15 08:08 UTC, merged