changes to 404 page
statisticsnorway/mimir pull request #539
Opened 2020-11-03 00:34 UTC by erikgus

2020-11-03 07:00 UTC, ssb-cgn requested changes
Missing searchfield and logo

2020-11-04 07:20 UTC, ssb-cgn commented on src/main/resources/react4xp/_entries/Search.jsx
> +      />
add value="" to avoid error in console.log

2020-11-04 07:21 UTC, ssb-cgn commented on src/main/resources/site/error/error.es6
>    assetUrl
getContent is not used

2020-11-04 07:21 UTC, ssb-cgn commented on src/main/resources/site/error/error.es6
>    getLanguage
getLanguage not used

2020-11-04 07:29 UTC, ssb-cgn requested changes
Have added som comments that should be fixed.

2020-11-04 11:44 UTC, erikgus commented on src/main/resources/site/error/error.es6
>    assetUrl
removed

2020-11-04 11:44 UTC, erikgus commented on src/main/resources/site/error/error.es6
>    getLanguage
removed

2020-11-04 11:55 UTC, ssb-cgn approved these changes
👍

2020-11-04 12:15 UTC, merged