moved button and added confirmation message
statisticsnorway/mimir pull request #743
Opened 2021-01-29 13:38 UTC by erikgus

2021-02-03 08:55 UTC, ssb-cgn commented on src/main/resources/react4xp/_entries/Dashboard/containers/DataQueries/DataQueryTable.jsx
> +          <Button variant="secondary" onClick={props.onHide}>Avbryt</Button>
kanskje bytte til onClick={() => setModalShow(false)} , får en varsel på at onHide is missing in props validation

2021-02-03 08:56 UTC, ssb-cgn commented on src/main/resources/react4xp/_entries/Dashboard/containers/DataQueries/DataQueryTable.jsx
>      const ids = dataQueries.filter((q) => !q.loading).map((q) => q.id)
Legge til lukk modal før den begynner oppdatering :)

2021-02-03 08:58 UTC, ssb-cgn requested changes
Add close modal when updating

2021-02-03 21:38 UTC, erikgus commented on src/main/resources/react4xp/_entries/Dashboard/containers/DataQueries/DataQueryTable.jsx
>      const ids = dataQueries.filter((q) => !q.loading).map((q) => q.id)
done

2021-02-04 07:48 UTC, ssb-cgn approved these changes
Nnice 👍

2021-02-04 11:01 UTC, merged