MIMIR-364: Add preview content link on the dashboard
statisticsnorway/mimir pull request #757
Opened 2021-02-03 12:46 UTC by itemodahl

2021-02-04 11:56 UTC, Glenruben commented
Denne funker ikke helt som den skal. Urlen blir feil. 
Innholdet på dashboard får denne urlen for preview: https://i.utv.ssb.no/admin/site/preview/default/draft/ssb/testemne/statistikk/test-statistikk-cgn
Den bør ha denne adressen: https://i.utv.ssb.no/xp/admin/site/preview/default/draft/ssb/testemne/statistikk/test-statistikk-cgn

Altså /xp/ før urlen.

2021-02-04 11:57 UTC, Glenruben requested changes
Se kommentar.

2021-02-09 10:18 UTC, itemodahl commented
La inn en config for å evt endre "base" urlen til preview. Default går til /xp/admin.

2021-02-11 12:54 UTC, Glenruben approved these changes

2021-02-11 13:28 UTC, merged