Mimir 385 frontpage statistics list
statisticsnorway/mimir pull request #894
Opened 2021-03-23 14:32 UTC by itemodahl

2021-03-23 15:01 UTC, Garlov requested changes

2021-03-23 15:01 UTC, Garlov commented on src/main/resources/assets/styles/_nextStatisticsReleases.scss
> +        border-top: 2px solid black;
see jira for list of style missmatches

2021-03-24 09:16 UTC, Garlov approved these changes
👍

2021-04-07 10:21 UTC, ssb-cgn commented on src/main/resources/site/parts/releasedStatistics/releasedStatistics.ts
> +    .setId('nextStatisticsReleases')
Maybe change from nextStatisticsReleases to previousStatisticsReleases?

2021-04-07 13:22 UTC, ssb-cgn commented on src/main/resources/site/parts/releasedStatistics/releasedStatistics.ts
> +  const groupedByYearMonthAndDay: GroupedBy<GroupedBy<GroupedBy<PreparedStatistics>>> = {}
This get doble dates if releases gets over 2 year

2021-04-07 13:23 UTC, ssb-cgn requested changes
Look at doble dates if dates from two years

2021-04-08 14:05 UTC, ssb-cgn commented on src/main/resources/react4xp/_entries/ReleasedStatistics.jsx
> +      <Title size={3}>Ny statistikk</Title>
Bør være en frase

2021-04-08 14:07 UTC, ssb-cgn commented on src/main/resources/site/i18n/phrases.properties
> +period.generic = tall for {0}
Må legge til disse i alle frasefiler

2021-04-08 14:14 UTC, ssb-cgn commented on src/main/resources/react4xp/_entries/ReleasedStatistics.jsx
> +                <Link href={`/${release.shortName}`} linkType='header'>{release.name}</Link>
På engelsk forside må linken gå til /en/shortname

2021-04-08 14:16 UTC, ssb-cgn requested changes
Need english phrases and som small fixes as i comment

2021-04-14 07:41 UTC, ssb-cgn commented on src/main/resources/site/i18n/phrases_en.properties
> +and = and
Denne mangler i 2 frasefiler

2021-04-14 08:09 UTC, ssb-cgn approved these changes
God job 🥇

2021-04-14 08:17 UTC, merged